# Copyright (c) 2023 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================
FROM ubuntu:24.04 AS base

ARG TAG=main

RUN apt-get update \ 
    && apt-get upgrade -y \ 
    && apt-get install -y --no-install-recommends \
    g++-11 \
    gcc-11 \
    make \
    wget \
    vim \
    libnuma-dev \
    numactl \
    git \
    pkg-config \
    software-properties-common \
    python3-pip \
    python3.12-dev \
    gcc-13 \
    g++-13 \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 60 \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 60 \
    && update-alternatives --install /usr/bin/python python /usr/bin/python3 60 \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /usr/lib/python3.12/EXTERNALLY-MANAGED

RUN pip install --no-cache-dir torch==2.3.0+cpu --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir cmake==3.26.1 transformers==4.43.3 sentencepiece==0.2.0 accelerate==0.31.0 numpy==1.26.4 protobuf tiktoken transformers-stream-generator einops \
    && ln -s /usr/bin/python3.8/lib/python3.8/site-packages/cmake/data/bin/cmake /usr/bin/cmake

# Install oneCCL
RUN git clone https://github.com/oneapi-src/oneCCL.git /tmp/oneCCL \
    && cd /tmp/oneCCL \
    && git checkout 2021.10 \
    && sed -i 's/cpu_gpu_dpcpp/./g' cmake/templates/oneCCLConfig.cmake.in \
    && mkdir build \
    && cd build \
    && cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/oneCCL -DCMAKE_C_COMPILER=/usr/bin/gcc-11 -DCMAKE_CXX_COMPILER=/usr/bin/g++-11 \
    && make -j install \
    && cd /root/ \
    && rm -rf /tmp/oneCCL \
    && echo "source /usr/local/oneCCL/env/setvars.sh" >> ~/.bashrc

WORKDIR /root/

RUN git clone --depth 1 -b ${TAG} https://github.com/intel/xFasterTransformer.git

FROM base as builder

SHELL ["/bin/bash", "-c"]
WORKDIR /root/xFasterTransformer

RUN source /usr/local/oneCCL/env/setvars.sh \
    && mkdir build \ 
    && cd build/ \
    && cmake .. \
    && mv /root/xFasterTransformer/3rdparty/mkl/local/* /root/xFasterTransformer/3rdparty/mkl/ \
    && make -j \
    && cd /root/xFasterTransformer \
    && python setup.py egg_info bdist_wheel --verbose


FROM base

COPY --from=builder /root/xFasterTransformer/dist/xfastertransformer-1.8.2-cp312-cp312-linux_x86_64.whl /tmp/
COPY --from=builder /root/xFasterTransformer/build/libxfastertransformer.so /usr/local/xft/lib/
COPY --from=builder /root/xFasterTransformer/build/libxft_comm_helper.so /usr/local/xft/lib/
COPY --from=builder /root/xFasterTransformer/include /usr/local/xft/include

RUN pip install /tmp/xfastertransformer-*.whl  --no-cache-dir \
    && rm -rf /tmp/xfastertransformer-*.whl

ENV LD_PRELOAD=/usr/local/lib/python3.12/dist-packages/xfastertransformer/libiomp5.so

